// <auto-generated />
using System;
using MarsRoverWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarsHoverWebApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarsRoverWebApplication.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeadingTo")
                        .HasColumnType("int");

                    b.Property<string>("MaxGridSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MovimentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NavigationSteps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoverId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoverId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MarsRoverWebApplication.Models.Rover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rovers");
                });

            modelBuilder.Entity("MarsRoverWebApplication.Models.Location", b =>
                {
                    b.HasOne("MarsRoverWebApplication.Models.Rover", "Rover")
                        .WithMany("Locations")
                        .HasForeignKey("RoverId");

                    b.Navigation("Rover");
                });

            modelBuilder.Entity("MarsRoverWebApplication.Models.Rover", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
